### ISSUE TITLE
巧用对象

### ISSUE THREAD

**Issue by Ficks** [Advanced-Frontend/Daily-Interview-Question#170]
var obj = {};
      function deepArr(arr) {
        for (let i = 0; i < arr.length; i++) {
          if (Array.isArray(arr[i])) {
            deepArr(arr[i]);
          } else {
            obj[arr[i]] = arr[i];
          }
        }
      }
      deepArr(arr);
      console.log(obj);
      console.log(Object.keys(obj));

**Comment by wingmeng** [comment]
ha?
