### ISSUE TITLE
已知一个数组[1,2,3]，不能用遍历数组的各种方法，去依次打印数组的每一个元素

### ISSUE THREAD

**Issue by flyfox11** [Advanced-Frontend/Daily-Interview-Question#186]
已知一个数组[1,2,3]，不能用遍历数组的各种方法，去依次打印数组的每一个元素

**Comment by nanajs** [comment]
function con(arr) {
  var a = arr.splice(0, 1);
  if (a) {
    console.log(a[0]);
    con(arr);
  } else {
    return
  }
}

**Comment by WunGCQ** [comment]
walk = (arr,i=0,cb=console.log)=>{ 
 if(i < arr.length) {
    cb(arr[i]);
    walk(arr,i+1,cb);
  }
};

walk([1,2,3]);

**Comment by yygmind** [comment]
老哥，麻烦提 PR
