### ISSUE TITLE
```js

### ISSUE THREAD

**Issue by HupuJrs001** [Advanced-Frontend/Daily-Interview-Question#204]
```js
const str = '1,2,3,5,7,8,10;

const transformStr = ( str ) => '1~3,5,7~8,10';
```
😈😈😈😈😈😈😈

_Originally posted by @Vibing in https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/201#issuecomment-513616995_

**Comment by AdamEleven** [comment]
这是我看了这么多答案中最简洁的回答, 也是复杂度最低的
