### ISSUE TITLE
![image](https://user-images.githubusercontent.com/23090200/64087714-cd8b4b00-cd70-11e9-8580-154d4e733028.png)

### ISSUE THREAD

**Issue by weiweixuan** [Advanced-Frontend/Daily-Interview-Question#267]
![image](https://user-images.githubusercontent.com/23090200/64087714-cd8b4b00-cd70-11e9-8580-154d4e733028.png)

_Originally posted by @flyfox11 in https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/266#issuecomment-526985060_

写的太优秀了，爆赞！！！

**Comment by XJawher** [comment]
请你不要随便开 issue !!!
请你不要随便开 issue !!!
请你不要随便开 issue !!!
请你不要随便开 issue !!!
