### ISSUE TITLE
为什么会这样，求大佬科普

### ISSUE THREAD

**Issue by EstherHuo** [Advanced-Frontend/Daily-Interview-Question#3]
![image](https://user-images.githubusercontent.com/26532175/51506001-e15af000-1e24-11e9-973e-a8c2961909ad.png)

**Comment by EstherHuo** [comment]
- [ ]

**Comment by machangzhi** [comment]
parseInt(string, radix)
string | 必需。要被解析的字符串。
radix | 可选。表示要解析的数字的基数。该值介于 2 ~ 36 之间。如果省略该参数或其值为 0，则数字将以 10 为基础来解析。如果它以 “0x” 或 “0X” 开头，将以 16 为基数。如果该参数小于 2 或者大于 36，则 parseInt() 将返回 NaN。
parseFloat(string)
string | 必需。要被解析的字符串。

**Comment by Aiyoweioo** [comment]
['1', '2','3'].map(parseInt) 等价于 parseInt('1',0) = 1, parseInt('2',1) = NaN, parseInt('3',2) = NaN
