### ISSUE TITLE
146.如何定义a变量，才能使a==1&a==2

### ISSUE THREAD

**Issue by huiyuye** [Advanced-Frontend/Daily-Interview-Question#303]

**Comment by GitHdu** [comment]
```
var a = {
  value:0,
  [Symbol.toPrimitive] () {
  return ++this.value
}
}
```

**Comment by muzishuiji** [comment]
这一题主要是考擦隐式类型转换
方案一:  
  var a = {
      value: [1,2],
      valueOf() {
        return this.value.shift();
      }
    }

方案二:  
  var a = {
      value: [1,2],
      [Symbol.toPrimitive]() {
        return this.value.shift();
      }
    }

**Comment by yygmind** [comment]
已有
