### ISSUE TITLE
假如有这么一段代码

### ISSUE THREAD

**Issue by 13353327353** [Advanced-Frontend/Daily-Interview-Question#318]
假如有这么一段代码
```javascript
new Promise(resolve => {
    resolve(1);
    Promise.resolve().then(() => console.log(2));
    Promise.resolve().then(() => console.log(5));
}).then(t => console.log(t));
```
请问为什么输出结果是2,5,1呢？
`resolve(1)`  之后，不应该是优先注册了外部 `.then` 的回调吗？
还是说内部的 `Promise` 是同步执行的？

_Originally posted by @ftv031 in https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/19#issuecomment-554197562_

resolve 只是把改变了Promise的status  然后把1存起来了 并不是直接执行then ， 而是then之后看到状态是resolved才直接执行

**Comment by libin1991** [comment]
promise需要将里面的代码都执行完才会到自己的then
```
 resolve(1);
    Promise.resolve().then(() => console.log(2));
    Promise.resolve().then(() => console.log(5));
```
