### ISSUE TITLE
第28题

### ISSUE THREAD

**Issue by 34678** [Advanced-Frontend/Daily-Interview-Question#32]
### cooki劫持
https://g2ex.github.io/2015/06/29/Cookie-and-Cookie-Injection/
1攻击者通过xss拿到用户的cookie然后就可以伪造cookie了。
2或者通过csrf在同个浏览器下面通过浏览器会自动带上cookie的特性
在通过 用户网站-攻击者网站-攻击者请求用户网站的方式 浏览器会自动带上cookie
但是token
1 不会被浏览器带上 问题2 解决
2 token是放在jwt里面下发给客户端的  而且不一定存储在哪里 不能通过document.cookie直接拿到，通过jwt+ip的方式 可以防止 被劫持 即使被劫持 也是无效的jwt
---------------
欢迎纠正

**Comment by yygmind** [comment]
移步到这里：https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/31
