### ISSUE TITLE
第 31 题：改造下面的代码，使之输出0 - 9，写出你能想到的所有解法。

### ISSUE THREAD

**Issue by suguoyao** [Advanced-Frontend/Daily-Interview-Question#44]
方法一
``` javascript
for (let i = 0; i< 10; i++){
    setTimeout(() => {
	console.log(i);
    }, 1000)
}
```

方法二
```  javascript
for (var i = 0; i< 10; i++){
    (function(i){
       setTimeout(() => {
	console.log(i);
    }, 1000)
  })(i)
}
```

**Comment by suguoyao** [comment]
方法三：
``` javascript
for (var i = 0; i < 10; i++) {
    (function () {
        var j = i;
         setTimeout(() => {
         console.log(j);
      }, 1000)
   })()
}
```

**Comment by gto999** [comment]
for (var i = 0; i< 10; i++){
    setTimeout((() => {
	console.log(i);
    })(i), 1000)
}

**Comment by jefferyE** [comment]
> ```js
> // 解法一：
>for (let i = 0; i< 10; i++){
>   setTimeout(() => {
>     console.log(i);
>   }, 1000)
>}
> ```
> ```js
> // 解法二：
>for (var i = 0; i< 10; i++){
>   ((i) => {
>	  setTimeout(() => {
 >       console.log(i);
 >     }, 1000)
 >  })(i)
>}
> ```

**Comment by suguoyao** [comment]
方法四：
``` javascript
for (var i = 0; i< 10; i++){
    setTimeout(console.log, 1000, i)
}
```

**Comment by wangshaowen** [comment]
这样可以么
### 
        var arr = [];
        for (var i = 0; i < 10; i++) {
            arr[i] = i
            setTimeout(()=>{
                console.log(arr.shift())
            })
        }

**Comment by jjeejj** [comment]
**使用一个变量保存 i **
```js
for (var i = 0; i< 10; i++){
    let j = i;
    setTimeout(() => {
	console.log(j);
    }, 1000)
}
```

**Comment by jjeejj** [comment]
> 这样可以么
> 
> ```
>     var arr = [];
>     for (var i = 0; i < 10; i++) {
>         arr[i] = i
>         setTimeout(()=>{
>             console.log(arr.shift())
>         })
>     }
> ```

@wangshaowen 能达到目的，想法很好啊 ，但是引入了数组，性能损失了一部分

**Comment by wangshaowen** [comment]
@jjeejj 谢谢大佬指点

**Comment by MoveZZG** [comment]
> > 这样可以么
> > ```
> >     var arr = [];
> >     for (var i = 0; i < 10; i++) {
> >         arr[i] = i
> >         setTimeout(()=>{
> >             console.log(arr.shift())
> >         })
> >     }
> > ```
> 
> @wangshaowen 能达到目的，想法很好啊 ，但是引入了数组，性能损失了一部分

可以说符合题意了

**Comment by ylfeng250** [comment]
我觉得封装一个函数也是可以
```js
function pprint(i){setTimeout(()=>{console.log(i)},1000)}
for(var i=0;i<10;i++){pprint(i)}
```

**Comment by yygmind** [comment]
已有 issue，可前往此处查看 https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/43

**Comment by MiaLeung01** [comment]
1. Closures
```
for (var i = 0; i < 10; i++) {
  ((i) => {
    setTimeout(() => { 
      console.log(i);
    }, 1000);
  })(i);
}

for (var i = 0; i < 10; i++) {
  setTimeout((i) => { 
      console.log(i);
  }, 1000, i);
}
```
2. let, let statement declares a block scope local variable
```
for (let i = 0; i< 10; i++){
   setTimeout(() => {
   console.log(i);
   }, 1000)
}
```
3. use array
```
var arr = [];
for (var i = 0; i< 10; i++){
   arr.unshift(i);
   setTimeout(() => {
   console.log(arr.pop());
   }, 1000);
}
```

**Comment by xufeiayang** [comment]
> ```js
> for (var i = 0; i< 10; i++){
>     setTimeout(console.log, 1000, i)
> }
> ```

秀儿，是你吗

**Comment by prefertwo** [comment]
> 这样可以么
> 
> ```
>     var arr = [];
>     for (var i = 0; i < 10; i++) {
>         arr[i] = i
>         setTimeout(()=>{
>             console.log(arr.shift())
>         })
>     }
> ```

你这个代码可以跑通达到要求，但是不通用，当 i 不从 0 开始就不行了。而使用let 和闭包这两种写法，是可以的。
最好还是要改成通用的方法，比如外面再声明一个从零开始的变量 m。
let arr = [];
let m = 0;
for(var i=7;i<10;i++) {
  arr[m] = i;
  m++;
  setTimeout(function () {
    console.log(arr.shift())
  }, 1000)
}
输出：7、8、9

**Comment by eileenyuling** [comment]
用Promise也可以
for (var i=0; i<10; i++) {
	Promise.resolve(i).then((res) => {
		setTimeout(() => {
			console.log(res)
		}, 1000)
	})
}
