### ISSUE TITLE
第171题：event loop 下面代码段的输出？bilibili

### ISSUE THREAD

**Issue by yellowjian** [Advanced-Frontend/Daily-Interview-Question#468]
event loop 
`var date = new Date()
console.log(1, new Date() - date)
setTimeout(() => {console.log(2, new Date() - date)}, 500)
Promise.resolve().then(console.log(3, new Date() - date))
while(new Date() - date < 1000) {}
console.log(4, new Date() - date)`

**Comment by yellowjian** [comment]
求上面的输出顺序和输出值

**Comment by sisterAn** [comment]
感谢补充，已记录
