### ISSUE TITLE
我的答案

### ISSUE THREAD

**Issue by haipingzi** [Advanced-Frontend/Daily-Interview-Question#479]
function getIndex(arr) {
      const [, minIndex] = arr.reduce(
        ([min, minIndex], el, index) => {
          if (el > 0 && (minIndex === -1 || min > el)) {
            return [el, index];
          }
          return [min, minIndex];
        },
        [null, -1],
      );
      return minIndex;
    }

**Comment by sisterAn** [comment]
这个是哪一题的解答？
