### ISSUE TITLE
第 43 题：使用 sort() 对数组 [3, 15, 8, 29, 102, 22] 进行排序

### ISSUE THREAD

**Issue by jiaweixianxian** [Advanced-Frontend/Daily-Interview-Question#68]
let array = [3, 15, 8, 29, 102, 22];
            console.log(array.sort((a, b) => {
                return a - b;
            })) //升序

            console.log(array.sort((a, b) => {
                return b - a
            })) //降序

**Comment by jiaweixianxian** [comment]
> ```
>         let array = [3, 15, 8, 29, 102, 22];
>         console.log(array.sort((a, b) => {
>             return a - b;
>         })) //升序
> 
>         console.log(array.sort((a, b) => {
>             return b - a
>         })) //降序
> ```
知识点：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by yygmind** [comment]
已有Issue，详情查看 https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/66
