### ISSUE TITLE
第44题 HTTPS握手

### ISSUE THREAD

**Issue by zhiwenxuan** [Advanced-Frontend/Daily-Interview-Question#72]
### 握手要解决的问题
1. 客户端和服务器身份的互相确认
2. 协商之后通信中对称加密的秘钥

### 握手流程
![HTTPS三次握手](http://www.ruanyifeng.com/blogimg/asset/201402/bg2014020502.png)

#### 步骤1： 客户端发出请求（ClientHello）
首先，客户端（通常是浏览器）先向服务器发出加密通信的请求，这被叫做ClientHello请求。  
在这一步，客户端主要向服务器提供以下信息。  
```
1. 客户端支持的SSL的指定版本
2. 客户端产生的随机数（Client Random, 稍后用于生成"对话密钥"
3. 客户端支持的加密算法
```

#### 步骤2：服务器回应（SeverHello）
服务器收到客户端请求后，向客户端发出回应，这叫做SeverHello。服务器的回应包含以下内容。  
```
1. 确认使用的加密通信协议版本，比如TLS 1.0版本。如果浏览器与服务器支持的版本不一致，服务器关闭加密通信。
2. 一个服务器生成的随机数(Server Random)，稍后用于生成"对话密钥"。
3. 确认使用的加密方法，比如RSA公钥加密。
4. 服务器证书
```
除了上面这些信息，如果服务器需要确认客户端的身份，就会再包含一项请求，要求客户端提供"客户端证书"。比如，金融机构往往只允许认证客户连入自己的网络，就会向正式客户提供USB密钥，里面就包含了一张客户端证书。  

**第一次握手结束**  

#### 步骤3：客户端回应
客户端收到服务器回应以后，首先验证服务器证书。如果证书不是可信机构颁布、或者证书中的域名与实际域名不一致、或者证书已经过期，就会向访问者显示一个警告，由其选择是否还要继续通信。

如果证书没有问题，客户端就会从证书中取出服务器的公钥。然后，向服务器发送下面三项信息。
```
1. 一个随机数（pre-master key）, 稍后用于生成"对话密钥"。
2. 编码改变通知，表示随后的信息都将用双方商定的加密方法和密钥发送。
3. 客户端握手结束通知，表示客户端的握手阶段已经结束。这一项同时也是前面发送的所有内容的hash值，用来供服务器校验。
```
上面第一项的随机数，是整个握手阶段出现的第三个随机数，又称"pre-master key"。有了它以后，客户端和服务器就同时有了三个随机数，接着双方就用事先商定的加密方法，各自生成本次会话所用的同一把"会话密钥"。

**第二次握手结束**  

步骤4：服务器的最后回应
服务器收到客户端的第三个随机数pre-master key之后，计算生成本次会话所用的"会话密钥"。然后，向客户端最后发送下面信息。

1. 编码改变通知，表示随后的信息都将用双方商定的加密方法和密钥发送。
2. 服务器握手结束通知，表示服务器的握手阶段已经结束。这一项同时也是前面发送的所有内容的hash值，用来供客户端校验。
至此，整个握手阶段全部结束。接下来，客户端与服务器进入加密通信，就完全是使用普通的HTTP协议，只不过用"会话密钥"加密内容，也就是对称加密。

**第三次握手结束**

## 以上是部分内容，**完整内容**可以查看我的 **[github 笔记](https://github.com/zhiwenxuan/my-web-note/edit/master/%E7%BD%91%E7%BB%9C%E5%8D%8F%E8%AE%AE/https.md)**，里面有面试常考知识点的总结，欢迎Star

**Comment by yygmind** [comment]
已有issues，已第一条为准https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/70
