### ISSUE TITLE
46:小菜解析

### ISSUE THREAD

**Issue by MrRENGE** [Advanced-Frontend/Daily-Interview-Question#75]
结果最后变为一个稀疏数组[,,1,2]。
因为在对象中加入splice属性方法，和length属性后。这个对象变成一个类数组。属性名称可转换为数字时，会映射成为索引下标。所以对象实际可这样描述：[,,3,4],然后继续执行length 属性复制，length 原来值为4，length：2 语句将数组截断成为长度为2的数组。此时数组为[,,]。接着push（1）、push (2)。数组追加两个值，[,,1,2]。小菜看法，有错望指正！！！

**Comment by yygmind** [comment]
更多查看 https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/76

**Comment by Jesseszhang** [comment]
> 结果最后变为一个稀疏数组[,,1,2]。
> 因为在对象中加入splice属性方法，和length属性后。这个对象变成一个类数组。属性名称可转换为数字时，会映射成为索引下标。所以对象实际可这样描述：[,,3,4],然后继续执行length 属性复制，length 原来值为4，length：2 语句将数组截断成为长度为2的数组。此时数组为[,,]。接着push（1）、push (2)。数组追加两个值，[,,1,2]。小菜看法，有错望指正！！！

正解！
var foo = {
    '1': 'Python',
    '8': 'Scala',
    length: 10
}
Array.from(foo)
 [undefined, "Python", undefined, undefined, undefined, undefined, undefined, undefined, "Scala", undefined]
var foo = {
    '1': 'Python',
    '8': 'Scala',
    length: 2
}
Array.from(foo)
[undefined, "Python"]  
是要看length的长度的

**Comment by TheHtmler** [comment]
请教下，splice是如何将对象转为类数组的
