### ISSUE TITLE
第 56 题：要求设计 LazyMan 类，实现以下功能。

### ISSUE THREAD

**Issue by zhangxh6931** [Advanced-Frontend/Daily-Interview-Question#99]
function Man(name) {
      this.name = name;
      console.log('I am' + this.name)
    }

    Man.prototype.eat = function(food) {
      setTimeout(function() {
        console.log('I am eating ' + food)
      }, 0)
      
      return this
    }

    Man.prototype.sleep = function(time) {

      setTimeout(function() {
        this.sleepFirst(time)
      }.bind(this), 0)
      return this
    }

    Man.prototype.sleepFirst = function(time) {
      var oldTime = time
      var date = new Date().getTime()
      time = time * 1000
      while (new Date().getTime() -  date < time) {

      }

      console.log('等待了' + oldTime + 's')
      return this
    }

    function LazyMan(name) {
      return new Man(name)
    }

**Comment by saxon111** [comment]
。
